//go:build ignore

// Generates chroma.css — the syntax-highlighting palette for the code
// the markdown adapter renders in classes mode (chromahtml.WithClasses,
// see internal/adapter/outbound/markdown). Output is committed; rerun
// via `go generate ./internal/adapter/inbound/web` after changing the
// styles below or upgrading chroma.
//
// Two palettes because page.html declares `color-scheme: light dark`:
// github for light, github-dark wrapped in a prefers-color-scheme
// media query.
package main

import (
	"bytes"
	"fmt"
	"os"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

func main() {
	formatter := chromahtml.New(chromahtml.WithClasses(true))

	var buf bytes.Buffer
	buf.WriteString("/* GENERATED by gen_chroma_css.go — do not edit. `go generate ./internal/adapter/inbound/web` */\n")

	light := styles.Get("github")
	if err := formatter.WriteCSS(&buf, light); err != nil {
		fmt.Fprintln(os.Stderr, "write light css:", err)
		os.Exit(1)
	}

	buf.WriteString("@media (prefers-color-scheme: dark) {\n")
	dark := styles.Get("github-dark")
	if err := formatter.WriteCSS(&buf, dark); err != nil {
		fmt.Fprintln(os.Stderr, "write dark css:", err)
		os.Exit(1)
	}
	buf.WriteString("}\n")

	if err := os.WriteFile("static/chroma.css", buf.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write chroma.css:", err)
		os.Exit(1)
	}
}
